project_id = "okxnlbndsifsrisrgcst"

[functions.import-validate]
verify_jwt = false

[functions.import-publish]
verify_jwt = false

[functions.settings-merge]
verify_jwt = false

[functions.import-normalize]
verify_jwt = false
